root = "../"
tmp_dir = "../tmp"

[build]
bin = "tmp/main"
cmd = "templ generate --path ../internal/view && go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["node_modules"]
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
