// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package form

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AddUser() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/auth/passkeys/create\"><fieldset><div class=\"table rows\"><div><label for=\"username\">Username</label> <input id=\"username\" name=\"username\" type=\"text\" placeholder=\"Username\" required></div><div><label for=\"email\">Email</label> <input id=\"email\" name=\"email\" type=\"email\" placeholder=\"Email\" required></div><div><label for=\"name\">Full name</label> <input id=\"name\" name=\"name\" type=\"text\" autocomplete=\"name\" placeholder=\"given-name\" required></div></div><hr><input type=\"submit\" value=\"Create User\"></fieldset></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
